spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config/{application},classpath:/config/{application}-{profile},
server:
    port: 8888
logging:
    level:
        org.springframework.cloud: debug
       # org.springframework.web: debug
management:
    endpoint:
        health:
            show-details: always
        mappings:
            enabled: true